[profile.default]
src = "src"
out = "out"
libs = ["lib"]


remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
  "forge-std/=lib/forge-std/src/",
  "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "v2-core/=lib/v2-core/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
